# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77bb33d4d2cc013bfe77ffe94c51fa851e61a2f2bfc91692ac17a277150a54f15b40f6eee5d6a74db576ce58f26e836ab0ecd3a80ca141fcecc0c3a4f44aaf55

test:
  secret_key_base: 57302e5402e86fb7fd54a98610dfc93b623931e5fce0c33547fbe298fb34274353504d990e84a0dfc4cae0d89a194c9798776520d9fb717c62f62080a89f86b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
